# Generated by Django 3.2.6 on 2021-08-04 07:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('pokemon', '0001_initial'), ('pokemon', '0002_auto_20210804_0628'), ('pokemon', '0003_auto_20210804_0636'), ('pokemon', '0004_pokemonspecies_type_set'), ('pokemon', '0005_damagemultiplier'), ('pokemon', '0006_auto_20210804_0652')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
            options={
                'verbose_name_plural': 'Pokemon species',
            },
        ),
        migrations.CreateModel(
            name='PokemonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=16)),
                ('level', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemon_set', to='pokemon.pokemonspecies')),
            ],
            options={
                'verbose_name_plural': 'Pokemon',
            },
        ),
        migrations.AddField(
            model_name='pokemonspecies',
            name='type_set',
            field=models.ManyToManyField(related_name='species_set', to='pokemon.PokemonType'),
        ),
        migrations.CreateModel(
            name='DamageMultiplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiplier', models.FloatField()),
                ('attacking_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strengths', to='pokemon.pokemontype')),
                ('receiving_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weaknesses', to='pokemon.pokemontype')),
            ],
        ),
        migrations.AddField(
            model_name='pokemonspecies',
            name='evolution_level',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='pokemonspecies',
            name='next_evolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preevolution_set', to='pokemon.pokemonspecies'),
        ),
    ]
